In [39]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [40]:
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

In [41]:
df=pd.read_csv(url,sep='\t',header=None,names=['tag','message'])

In [42]:
df.head()

    tag                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [43]:
df.shape

(5572, 2)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   tag      5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [45]:
df.isna().sum()

tag        0
message    0
dtype: int64

In [46]:
df['tag'] = df['tag'].str.strip().str.lower()
df['tag']=df['tag'].map({'ham' : 0, 'spam':1})

In [47]:
df.describe()

               tag
count  5572.000000
mean      0.134063
std       0.340751
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [48]:
df.head()

   tag                                            message
0    0  Go until jurong point, crazy.. Available only ...
1    0                      Ok lar... Joking wif u oni...
2    1  Free entry in 2 a wkly comp to win FA Cup fina...
3    0  U dun say so early hor... U c already then say...
4    0  Nah I don't think he goes to usf, he lives aro...

In [49]:
X=df['message']
y=df['tag']

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=15)

In [57]:
spam=Pipeline(
    [
        ('Vector',CountVectorizer(stop_words='english')),
        ('model',MultinomialNB())
    ]
)

In [51]:
"""
it can be use but CountVectorizer have bigger accuracy score now.
spam=Pipeline(
    [
        ('Vector',TfidfVectorizer(stop_words='english')),
        ('model',MultinomialNB())
    ]
)
"""

In [58]:
spam.fit(X_train,y_train)

Pipeline(steps=[('Vector', CountVectorizer(stop_words='english')),
                ('model', MultinomialNB())])

In [59]:
y_pred=spam.predict(X_test)

In [60]:
print(y_pred)

[0 1 0 ... 0 1 0]

In [61]:
accuracy_score(y_test,y_pred)

0.9764468371467026

In [56]:
print(confusion_matrix(y_test,y_pred))

[[3864    0]
 [ 258  336]]

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      3864
           1       0.95      0.87      0.91       594

    accuracy                           0.98      4458
   macro avg       0.96      0.93      0.95      4458
weighted avg       0.98      0.98      0.98      4458